version: 0.2

env:
  variables:
    TF_RECREATE_MISSING_LAMBDA_PACKAGE: false
    TF_IN_AUTOMATION: true
    %{ if tf_log != null }
    TF_LOG: ${tf_log}
    %{ endif }

phases:
  install:
    commands:
      - wget --no-verbose https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin
      - cd ${RESOURCES_PATH}
      - terraform init -input=false -no-color

  build:
    commands:
      # Place the scripts
      - mkdir -p /tmp/scripts/
      - aws s3 cp ${SCRIPTS_LOCATION} /tmp/scripts/ --recursive
      - chmod +x /tmp/scripts/*.sh
      - ls -al /tmp/scripts/

      # Run the drift check
      - /tmp/scripts/drift-check.sh

artifacts:
  files:
    - ${RESOURCES_PATH}*.txt
    - ${RESOURCES_PATH}*.json

cache:
  paths:
    - '.terraform/**/*'
